export const ACTIONS = {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',


    // 🔐 AUTH
    LOGIN: 'LOGIN',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REGISTER: 'REGISTER',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
    SECURITY_EVENT: 'SECURITY_EVENT',

    // 👤 USERS / PROFILE
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPLOAD_AVATAR: 'UPLOAD_AVATAR',

    // 🧑‍⚕️ STAFF
    CREATE_STAFF: 'CREATE_STAFF',
    UPDATE_STAFF: 'UPDATE_STAFF',
    DELETE_STAFF: 'DELETE_STAFF',

    // 🧑 PATIENTS
    CREATE_PATIENT: 'CREATE_PATIENT',
    UPDATE_PATIENT: 'UPDATE_PATIENT',
    DELETE_PATIENT: 'DELETE_PATIENT',

    // 💊 PRESCRIPTIONS
    CREATE_PRESCRIPTION: 'CREATE_PRESCRIPTION',
    DELETE_PRESCRIPTION: 'DELETE_PRESCRIPTION',

    CREATE_ROLE: 'CREATE_ROLE',
    UPDATE_ROLE: 'UPDATE_ROLE',
    DELETE_ROLE: 'DELETE_ROLE',

    // 📦 CONTAINERS
    ASSIGN_CONTAINER: 'ASSIGN_CONTAINER',
    UNASSIGN_CONTAINER: 'UNASSIGN_CONTAINER',
    UPDATE_CONTAINER_STATUS: 'UPDATE_CONTAINER_STATUS',

    // 📦 COMPARTMENTS / IoT
    FILL_COMPARTMENT: 'FILL_COMPARTMENT',
    CLEAR_COMPARTMENT: 'CLEAR_COMPARTMENT',

    // 💊 INTAKE
    TAKE_MEDICATION: 'TAKE_MEDICATION',
    UPDATE_INTAKE_STATUS: 'UPDATE_INTAKE_STATUS',

    // 🔔 NOTIFICATIONS
    SEND_NOTIFICATION: 'SEND_NOTIFICATION',
    MISSED_NOTIFICATION: 'MISSED_NOTIFICATION',
    OPEN_NOTIFICATION: 'OPEN_NOTIFICATION',

    // 📊 REPORTS
    EXPORT_PATIENTS: 'EXPORT_PATIENTS',
    EXPORT_STAFF: 'EXPORT_STAFF',
    EXPORT_CONTAINERS: 'EXPORT_CONTAINERS',
    EXPORT_TREATMENT: 'EXPORT_TREATMENT'
};