export const ACTIONS = {
    LOGIN: 'LOGIN',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTER: 'REGISTER',
    SECURITY_EVENT: 'SECURITY_EVENT',


    CREATE_PATIENT: 'CREATE_PATIENT',
    UPDATE_PATIENT: 'UPDATE_PATIENT',

    CREATE_PRESCRIPTION: 'CREATE_PRESCRIPTION',

    FILL_COMPARTMENT: 'FILL_COMPARTMENT',
    TAKE_MEDICATION: 'TAKE_MEDICATION'
};