export const ERROR_CODES = {

    // 🔐 AUTH
    USER_EXISTS: 'USER_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    SESSION_COMPROMISED: 'SESSION_COMPROMISED',

    WEAK_PASSWORD: 'WEAK_PASSWORD',

    // 📥 VALIDATION
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_INPUT: 'INVALID_INPUT',

    // 🔑 ACCESS
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    // 📦 GENERAL
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',

    // 📦 CONTAINERS
    CONTAINER_NOT_FOUND: 'CONTAINER_NOT_FOUND',
    CONTAINER_ALREADY_ASSIGNED: 'CONTAINER_ALREADY_ASSIGNED',

    // 📦 COMPARTMENTS
    COMPARTMENT_NOT_FOUND: 'COMPARTMENT_NOT_FOUND',
    COMPARTMENT_ALREADY_FILLED: 'COMPARTMENT_ALREADY_FILLED',
    COMPARTMENT_EMPTY: 'COMPARTMENT_EMPTY',

    // 💊 PRESCRIPTIONS
    PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',

    // 💊 INTAKE
    INTAKE_ALREADY_COMPLETED: 'INTAKE_ALREADY_COMPLETED',

    // 🔔 NOTIFICATIONS
    NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',

    // 🚦 RATE LIMIT
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

    // 💥 SERVER
    INTERNAL_ERROR: 'INTERNAL_ERROR'
};