export const ERROR_CODES = {
    USER_EXISTS: 'USER_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    SESSION_COMPROMISED: 'SESSION_COMPROMISED',

    WEAK_PASSWORD: 'WEAK_PASSWORD',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_INPUT: 'INVALID_INPUT',

    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',

    CONTAINER_NOT_FOUND: 'CONTAINER_NOT_FOUND',
    CONTAINER_ALREADY_ASSIGNED: 'CONTAINER_ALREADY_ASSIGNED',

    COMPARTMENT_NOT_FOUND: 'COMPARTMENT_NOT_FOUND',
    COMPARTMENT_ALREADY_FILLED: 'COMPARTMENT_ALREADY_FILLED',
    COMPARTMENT_EMPTY: 'COMPARTMENT_EMPTY',

    PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',

    INTAKE_ALREADY_COMPLETED: 'INTAKE_ALREADY_COMPLETED',

    NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',

    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
};